services:
  - type: web
    name: sustainify-v2
    env: node
    buildCommand: npm install && pip install requests
    startCommand: node Backend/src/index.js # Adjust if different
    nativeEnvironments:
      - type: python
        version: "3.11"